---
- name: Prepare CentOS Stream Host
  hosts: microshift-host
  become: true
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ microshift_hostname }}"
    - name: Ensure required system tools are present
      ansible.builtin.dnf:
        name:
          - podman
          - lvm2
        state: present

