- name: Deploy Apache Guacamole
  hosts: microshift-host
  gather_facts: false
  become: true
  tasks:

    - name: Create Guacamole Namespace
      ansible.builtin.command:
        cmd: "oc create namespace {{ guac.namespace }}"
      register: ns_create
      failed_when: false
      changed_when: "'created' in ns_create.stdout"
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Grant anyuid SCC to Guacamole namespace
      ansible.builtin.command:
        cmd: "oc adm policy add-scc-to-user anyuid -z default -n {{ guac.namespace }}"
      register: scc_result
      changed_when: "'added' in scc_result.stdout or 'already has' not in scc_result.stdout"
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Template All Components
      ansible.builtin.template:
        src: "{{ (playbook_dir + '/../templates/' + item + '.yaml.j2') | realpath }}"
        dest: "/tmp/{{ item }}.yaml"
        owner: "{{ microshift_admin  }}"
        group: "{{ microshift_admin  }}"
        mode: '0644'
      loop:
        - guacamole-pvc
        - guacamole-postgres-deploy
        - guacd-deploy
        - guacamole-deploy
        # - guacamole-services
        # - guacamole-route
      register: template_files
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Apply Manifests to MicroShift
      ansible.builtin.command:
        cmd: "oc apply -f /tmp/{{ item }}.yaml"
      loop:
        - guacamole-pvc
        - guacamole-postgres-deploy
        - guacd-deploy
        - guacamole-deploy
        # - guacamole-services
        # - guacamole-route
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Debug Infrastructure Status
      ansible.builtin.shell: |
        echo "--- PVC STATUS ---"
        oc get pvc -n {{ guac.namespace }}
        echo "--- POD STATUS ---"
        oc get pods -n {{ guac.namespace }}
      register: infra_debug
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Print Infra Debug
      ansible.builtin.debug:
        var: infra_debug.stdout_lines
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Wait for Guac DB to be Available
      ansible.builtin.command:
        cmd: "oc wait --for=condition=Available deployment/{{ guac.db.deployment }} -n {{ guac.namespace }} --timeout=120s"
      register: wait_guac_pgsql
      retries: 10
      delay: 5
      until: wait_guac_pgsql.rc == 0
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Wait for guacd to be Available
      ansible.builtin.command:
        cmd: "oc wait --for=condition=Available deployment/{{ guac.guacd.deployment }} -n {{ guac.namespace }} --timeout=120s"
      register: wait_guac
      retries: 10
      delay: 5
      until: wait_guac.rc == 0
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Wait for guacamole to be available
      ansible.builtin.command:
        cmd: "oc wait --for=condition=Available deployment/{{ guac.guacamole.deployment }} -n {{ guac.namespace }} --timeout=60s"
      register: wait_guac
      retries: 10
      delay: 5
      until: wait_guac.rc == 0
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Initialise Guacamole Database Schema
      ansible.builtin.shell:
        cmd: |
          # Find GUACAMOLE frontend pod
          GUACAMOLE_POD=$(oc get pods -n {{ guac.namespace }} -l app={{ guac.guacamole.deployment }} -o jsonpath='{.items[0].metadata.name}')

          # 2. Find POSTGRES pod
          PG_POD=$(oc get pods -n {{ guac.namespace }} -l app={{ guac.db.deployment }} -o jsonpath='{.items[0].metadata.name}')

          # 3. Exec into GUACAMOLE pod to get script, pipe natively through your host into the PG pod
          oc exec -n {{ guac.namespace }} $GUACAMOLE_POD -- /opt/guacamole/bin/initdb.sh --postgresql | \
          oc exec -i -n {{ guac.namespace }} $PG_POD -- env PGPASSWORD="{{ guac.db.password }}" psql -U "{{ guac.db.user }}" -d "{{ guac.db.deployment }}" -f -
      register: db_init_result
      failed_when:
        - db_init_result.rc != 0
        - "'already exists' not in db_init_result.stderr"
        - "'relation' not in db_init_result.stderr"
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Ensure pip is installed on CentOS Stream
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install required kubernetes Python library
      ansible.builtin.pip:
        name:
          - kubernetes
        state: present

    - name: Ensure Guacamole Service has named port for Route
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ guac.guacamole.deployment }}"
            namespace: "{{ guac.namespace }}"
          spec:
            selector:
              app: "{{ guac.guacamole.deployment }}"
            ports:
              - name: http
                protocol: TCP
                port: "{{ guac.guacamole.container.port }}"
                targetPort: "{{ guac.guacamole.container.targetport }}"
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Ensure Guacamole Database Service exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ guac.db.deployment }}"
            namespace: "{{ guac.namespace }}"
          spec:
            ports:
              - name: postgres
                protocol: TCP
                port: "{{ guac.db.port }}"
                targetPort: "{{ guac.db.port }}"
            selector:
              app: "{{ guac.db.deployment }}"
      become: true
      become_user: "{{ microshift_admin }}"

    - name: Create Route for Guacamole Web
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ guac.guacamole.deployment }}"
            namespace: "{{ guac.namespace }}"
            annotations:
              openshift.io/host.generated: "true"
          spec:
            host: "{{ guac.guacamole.hostname }}"
            to:
              kind: Service
              name: "{{ guac.guacamole.deployment }}"
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
      become: true
      become_user: "{{ microshift_admin }}"

